// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pkg/ports/ports.proto

package ports

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortDomainServiceClient is the client API for PortDomainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortDomainServiceClient interface {
	GetPort(ctx context.Context, in *PortId, opts ...grpc.CallOption) (*Port, error)
	UpsertPort(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Empty, error)
	UpsertPorts(ctx context.Context, opts ...grpc.CallOption) (PortDomainService_UpsertPortsClient, error)
}

type portDomainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortDomainServiceClient(cc grpc.ClientConnInterface) PortDomainServiceClient {
	return &portDomainServiceClient{cc}
}

func (c *portDomainServiceClient) GetPort(ctx context.Context, in *PortId, opts ...grpc.CallOption) (*Port, error) {
	out := new(Port)
	err := c.cc.Invoke(ctx, "/ports.PortDomainService/GetPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portDomainServiceClient) UpsertPort(ctx context.Context, in *Port, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ports.PortDomainService/UpsertPort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portDomainServiceClient) UpsertPorts(ctx context.Context, opts ...grpc.CallOption) (PortDomainService_UpsertPortsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortDomainService_ServiceDesc.Streams[0], "/ports.PortDomainService/UpsertPorts", opts...)
	if err != nil {
		return nil, err
	}
	x := &portDomainServiceUpsertPortsClient{stream}
	return x, nil
}

type PortDomainService_UpsertPortsClient interface {
	Send(*Port) error
	CloseAndRecv() (*PortSummary, error)
	grpc.ClientStream
}

type portDomainServiceUpsertPortsClient struct {
	grpc.ClientStream
}

func (x *portDomainServiceUpsertPortsClient) Send(m *Port) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portDomainServiceUpsertPortsClient) CloseAndRecv() (*PortSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PortSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortDomainServiceServer is the server API for PortDomainService service.
// All implementations must embed UnimplementedPortDomainServiceServer
// for forward compatibility
type PortDomainServiceServer interface {
	GetPort(context.Context, *PortId) (*Port, error)
	UpsertPort(context.Context, *Port) (*Empty, error)
	UpsertPorts(PortDomainService_UpsertPortsServer) error
	mustEmbedUnimplementedPortDomainServiceServer()
}

// UnimplementedPortDomainServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPortDomainServiceServer struct {
}

func (UnimplementedPortDomainServiceServer) GetPort(context.Context, *PortId) (*Port, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPort not implemented")
}
func (UnimplementedPortDomainServiceServer) UpsertPort(context.Context, *Port) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPort not implemented")
}
func (UnimplementedPortDomainServiceServer) UpsertPorts(PortDomainService_UpsertPortsServer) error {
	return status.Errorf(codes.Unimplemented, "method UpsertPorts not implemented")
}
func (UnimplementedPortDomainServiceServer) mustEmbedUnimplementedPortDomainServiceServer() {}

// UnsafePortDomainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortDomainServiceServer will
// result in compilation errors.
type UnsafePortDomainServiceServer interface {
	mustEmbedUnimplementedPortDomainServiceServer()
}

func RegisterPortDomainServiceServer(s grpc.ServiceRegistrar, srv PortDomainServiceServer) {
	s.RegisterService(&PortDomainService_ServiceDesc, srv)
}

func _PortDomainService_GetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortDomainServiceServer).GetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ports.PortDomainService/GetPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortDomainServiceServer).GetPort(ctx, req.(*PortId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortDomainService_UpsertPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Port)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortDomainServiceServer).UpsertPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ports.PortDomainService/UpsertPort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortDomainServiceServer).UpsertPort(ctx, req.(*Port))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortDomainService_UpsertPorts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortDomainServiceServer).UpsertPorts(&portDomainServiceUpsertPortsServer{stream})
}

type PortDomainService_UpsertPortsServer interface {
	SendAndClose(*PortSummary) error
	Recv() (*Port, error)
	grpc.ServerStream
}

type portDomainServiceUpsertPortsServer struct {
	grpc.ServerStream
}

func (x *portDomainServiceUpsertPortsServer) SendAndClose(m *PortSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portDomainServiceUpsertPortsServer) Recv() (*Port, error) {
	m := new(Port)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortDomainService_ServiceDesc is the grpc.ServiceDesc for PortDomainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortDomainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ports.PortDomainService",
	HandlerType: (*PortDomainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPort",
			Handler:    _PortDomainService_GetPort_Handler,
		},
		{
			MethodName: "UpsertPort",
			Handler:    _PortDomainService_UpsertPort_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpsertPorts",
			Handler:       _PortDomainService_UpsertPorts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/ports/ports.proto",
}
